# 00_check_env.ipynb

Sanity check untuk lingkungan Python + Jupyter + NumPy + Pandas + Matplotlib.

**Cara pakai:** jalankan tiap sel dari atas ke bawah. Jika semua sel berjalan tanpa error, environment sudah siap.


In [2]:
import sys, platform
import numpy as np
import pandas as pd
import matplotlib

print("Python :", sys.version)
print("Platform:", platform.platform())
print("NumPy  :", np.__version__)
print("Pandas :", pd.__version__)
print("Matplotlib:", matplotlib.__version__)


Python : 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Platform: Windows-10-10.0.26100-SP0
NumPy  : 2.3.2
Pandas : 2.3.2
Matplotlib: 3.10.5


In [1]:
# NumPy sanity test
import numpy as np
a = np.arange(9).reshape(3, 3)
b = np.ones((3, 3))
print("a =\n", a)
print("b =\n", b)
print("a @ b =\n", a @ b)


a =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a @ b =
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [3]:
# Pandas sanity test
import pandas as pd
df = pd.DataFrame({"category": ["A", "A", "B", "B"], "value": [10, 12, 8, 11]})
print(df)
print("\nMean value per category:")
print(df.groupby("category")["value"].mean())


  category  value
0        A     10
1        A     12
2        B      8
3        B     11

Mean value per category:
category
A    11.0
B     9.5
Name: value, dtype: float64


In [ ]:
# Matplotlib sanity test (akan muncul sebuah plot)
import matplotlib.pyplot as plt
plt.plot([1, 2, 3], [1, 4, 9])
plt.title("Sanity Plot")
plt.xlabel("x")
plt.ylabel("y^2")
plt.show()
